version: '3'
services:
    redis-master:
        image: 'redis:5.0-alpine'

    redis-sentinel:
        image: 'cerquide/redis-sentinel:latest'
        depends_on:
            - redis-master
        links:
            - redis-master

    postgres:
        image: 'postgres:9.6-alpine'
        environment:
            - POSTGRES_USER=pybossa
            - POSTGRES_PASSWORD=supersecretpassword

    # initializes the database
    db-init:
        image: 'cerquide/pybossa:latest'
        depends_on:
            - postgres
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@db/pybossa
            - REDIS_SENTINEL=redis-sentinel
            - REDIS_MASTER=mymaster
        links:
            - postgres:db
        command: sh -c "sleep 5 && python cli.py db_create"

    # TODO: create a separate scheduler process??
    #       command: rqscheduler --host redis-master
    # background worker process
    pybossa-bgworker:
        container_name: pybossa-bgworker
        image: 'cerquide/pybossa:latest'
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@db/pybossa
            - REDIS_SENTINEL=redis-sentinel
            - REDIS_MASTER=mymaster
        links:
            - redis-master
            - redis-sentinel
            - postgres:db
        command: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance

    pybossa:
        container_name: pybossa
        image: 'cerquide/pybossa:latest'
        depends_on:
            - db-init
        environment:
            - POSTGRES_URL=postgresql://pybossa:supersecretpassword@db/pybossa
            - REDIS_SENTINEL=redis-sentinel
            - REDIS_MASTER=mymaster
        links:
            - redis-master
            - redis-sentinel
            - postgres:db
        ports:
            - "8080:8080"

